# Generated by Django 4.1.2 on 2022-10-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_remove_list_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list',
            new_name='lista',
        ),
    ]
