# Generated by Django 4.1.2 on 2022-10-28 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_rename_list_item_lista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.list'),
        ),
    ]
